%YAML:1.0
---
# ###### CAMERA PARAMETERS ######
video width: 1280
video height: 720
camera fx: 749.8203735351562
camera fy: 749.7190551757812
camera cx: 640.7588500976562
camera cy: 364.8509216308594

distortion parameters: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0.07101956754922867, -0.09848150610923767,
       0.00043707378790713847, 0.0001285719481529668,
       0.039714131504297256 ]
# ###### TEMPLATE GENERATION SETTINGS ######
model folder: models/
model file ending: ".ply"
only use color modality: 1
in plane rotation starting angle: -180
in plane rotation stopping angle: 180
in plane rotation angle step: 5
distance start: 500
distance stop: 900
distance step: 200
icosahedron subdivisions: 3
# ###### TEMPLATE DETECTOR SETTINGS ######
detector threshold: 80
percent to pass check: 50
number of poses to compare: 1
distance to match to be considered same object: 45
ratio to determine if group is too small: 35
use depth improvement: 0
depth offset: 30
use icp: 0
icp subsampling factor: 2


